#!/usr/bin/env python3
"""Stage PC NPC SPR files needed by generated Region_S spawns.

Source of truth:
- Region_S files generated by scripts/jx_map_server_region_port.py
- PC NpcS.txt rows in Assets/StreamingAssets/Reference/PcNpc/npcs.txt
- PC client PACK data under /var/www/vltksource_new/01_tinh_kiem_source/source/00.src-tinh-kiem/bin/client/data

Raw SPR outputs are intentionally written to ignored StreamingAssets/Generated/NpcSprites.
Small committed JSON catalogs describe coverage and allow runtime/file audits.
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import shutil
import struct
import sys
import time
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

UNITY_ROOT = Path('/var/www/vltk-mobile')
PC_ROOT = Path('/var/www/vltksource_new/01_tinh_kiem_source/source/00.src-tinh-kiem')
JX_MAP_PORT = UNITY_ROOT / 'harness/.codex/skills/jx-map-port/scripts/jx_map_port.py'


def load_module(path: Path, name: str):
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f'Cannot import {path}')
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


jx = load_module(JX_MAP_PORT, 'jx_map_port_npc_spr')


def utc_now() -> str:
    return datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')


def make_meta(path: Path) -> None:
    meta = path.with_suffix(path.suffix + '.meta')
    if meta.exists():
        return
    meta.write_text(
        'fileFormatVersion: 2\n'
        f'guid: {uuid.uuid4().hex}\n'
        'DefaultImporter:\n'
        '  externalObjects: {}\n'
        '  userData:\n'
        '  assetBundleName:\n'
        '  assetBundleVariant:\n',
        encoding='utf-8')


def iter_region_s_files(region_root: Path):
    if not region_root.is_dir():
        return
    yield from region_root.glob('*/*_Region_S.dat')


def parse_region_s_template_ids(path: Path) -> list[int]:
    data = path.read_bytes()
    if len(data) < 4:
        return []
    section_count = struct.unpack_from('<I', data, 0)[0]
    if section_count < 4 or section_count > 20:
        return []
    header_size = 4 + section_count * 8
    if len(data) < header_size:
        return []
    npc_off, npc_len = struct.unpack_from('<II', data, 4 + 2 * 8)
    npc_start = header_size + npc_off
    if npc_len < 12 or npc_start + npc_len > len(data):
        return []
    count = struct.unpack_from('<I', data, npc_start)[0]
    pos = npc_start + 12
    result: list[int] = []
    for _ in range(count):
        if pos + 60 > npc_start + npc_len:
            break
        template_id = struct.unpack_from('<i', data, pos)[0]
        script_len = struct.unpack_from('<H', data, pos + 58)[0]
        result.append(template_id)
        pos += 60 + script_len
    return result


def read_npc_rows(path: Path) -> list[list[str]]:
    lines = path.read_text(encoding='utf-8', errors='ignore').splitlines()
    if lines and lines[0].lower().startswith('name\t'):
        lines = lines[1:]
    return [line.split('\t') for line in lines if line.strip()]


def read_text_lines(path: Path) -> list[str]:
    return path.read_text(encoding='gbk', errors='ignore').splitlines()


def npcres_dir(pc_root: Path) -> Path:
    return pc_root / 'Client 6.0/settings/npcres'


def load_npcres_paths(pc_root: Path) -> dict[str, str]:
    """Load CharacterName -> ResFilePath from PC settings/npcres character table."""
    result: dict[str, str] = {}
    root = npcres_dir(pc_root)
    if not root.is_dir():
        return result
    for path in root.glob('*.txt'):
        try:
            lines = read_text_lines(path)
        except Exception:
            continue
        if not lines or not lines[0].startswith('CharacterName\tCharacterType\tResFilePath'):
            continue
        for line in lines[1:]:
            cols = line.split('\t')
            if len(cols) < 3:
                continue
            name = cols[0].strip()
            res_path = cols[2].strip().strip('\\')
            if name and res_path:
                result.setdefault(name, res_path)
    return result


def load_npcres_sprite_rows(pc_root: Path) -> dict[str, list[str]]:
    """Load CharacterName -> SPR filenames from the PC ordinary-NPC resource table."""
    root = npcres_dir(pc_root)
    if not root.is_dir():
        return {}
    candidates: list[tuple[int, Path, list[str]]] = []
    for path in root.glob('*.txt'):
        try:
            lines = read_text_lines(path)
        except Exception:
            continue
        if not lines or not (lines[0].startswith('NpcList\t') or lines[0].startswith('CharacterName\t')):
            continue
        score = 0
        joined = '\n'.join(lines[:400])
        if 'ani063_st.spr' in joined and 'ani063_wlk.spr' in joined:
            score += 10
        if 'passerby001z.spr' in '\n'.join(lines):
            score += 10
        if lines[0].startswith('NpcList\t'):
            score += 5
        if 'FreeStand1' not in lines[0] and 'info' not in lines[0].lower():
            score += 3
        if score > 0:
            candidates.append((score, path, lines))
    if not candidates:
        return {}
    candidates.sort(key=lambda x: (x[0], x[1].stat().st_size), reverse=True)
    lines = candidates[0][2]
    result: dict[str, list[str]] = {}
    for line in lines[1:]:
        cols = line.split('\t')
        if not cols:
            continue
        name = cols[0].strip()
        sprites: list[str] = []
        seen: set[str] = set()
        for col in cols[1:]:
            value = col.strip().strip('"')
            if not value.lower().endswith('.spr'):
                continue
            if value not in seen:
                seen.add(value)
                sprites.append(value)
        if name and sprites:
            result[name] = sprites
    return result


def folder_for_res_type(res_type: str) -> str:
    value = (res_type or '').lower()
    if value.startswith('ani'):
        return 'animal'
    if value.startswith('boss'):
        return 'boss'
    if value.startswith('passerby'):
        return 'passerby'
    if value.startswith('critter'):
        return 'critter'
    return 'enemy'


def candidate_actions(res_type: str) -> list[str]:
    value = (res_type or '').lower()
    if value.startswith('passerby'):
        return ['wlk', 'st', 'st01', 'pst', 'die', 'st02', 'base']
    return ['wlk', 'st', 'die']


def path_for(res_type: str, action: str) -> str:
    folder = folder_for_res_type(res_type)
    if action == 'base':
        return fr'\spr\npcres\{folder}\{res_type}\{res_type}.spr'
    return fr'\spr\npcres\{folder}\{res_type}\{res_type}_{action}.spr'


def source_paths_for_res_type(res_type: str, npcres_paths: dict[str, str], npcres_sprites: dict[str, list[str]]) -> list[str]:
    base = npcres_paths.get(res_type)
    sprites = npcres_sprites.get(res_type)
    if base and sprites:
        return [fr'\{base}\{sprite}' for sprite in sprites]
    return [path_for(res_type, action) for action in candidate_actions(res_type)]


def action_from_path(path: str, res_type: str) -> str:
    stem = Path(path.replace('\\', '/')).stem
    prefix = f'{res_type}_'
    if stem == res_type:
        return 'base'
    return stem[len(prefix):] if stem.startswith(prefix) else stem


def collect_requirements(region_root: Path, npc_rows: list[list[str]], extra_template_ids: list[int],
                         extra_res_types: list[str]) -> dict[str, dict[str, Any]]:
    by_res: dict[str, dict[str, Any]] = {}
    template_ids = set()
    for region_file in iter_region_s_files(region_root):
        template_ids.update(parse_region_s_template_ids(region_file))
    template_ids.update(extra_template_ids)
    for template_id in sorted(template_ids):
        if template_id < 0 or template_id >= len(npc_rows):
            continue
        row = npc_rows[template_id]
        res_type = row[11].strip() if len(row) > 11 else ''
        if not res_type:
            continue
        entry = by_res.setdefault(res_type, {
            'resType': res_type,
            'folder': folder_for_res_type(res_type),
            'templateIds': [],
        })
        entry['templateIds'].append(template_id)
    for res_type in extra_res_types:
        if not res_type:
            continue
        by_res.setdefault(res_type, {
            'resType': res_type,
            'folder': folder_for_res_type(res_type),
            'templateIds': [],
        })
    return by_res


def extract_spr(index: dict[int, tuple[str, int, int, int]], source_path: str) -> bytes | None:
    uid = jx.g_filename2id(source_path.encode('gbk', errors='ignore'))
    loc = index.get(uid)
    if not loc:
        return None
    raw, method, dsize = jx.read_entry(loc)
    return jx.get_flat_spr(raw, method, dsize)


def client_package_order(pc_root: Path) -> list[Path]:
    client_root = pc_root / 'Client 6.0'
    data_dir = client_root / 'data'
    package_ini = client_root / 'package1.ini'
    result: list[Path] = []
    if package_ini.is_file():
        for line in package_ini.read_text(encoding='utf-8', errors='ignore').splitlines():
            line = line.strip()
            if not line or line.startswith('[') or '=' not in line:
                continue
            key, value = line.split('=', 1)
            if not key.strip().isdigit():
                continue
            pak = data_dir / value.strip()
            if pak.is_file():
                result.append(pak)
    if not result:
        result = sorted(data_dir.glob('*.pak'))
    return result


def build_priority_index(package_paths: list[Path]) -> dict[int, tuple[str, int, int, int]]:
    index: dict[int, tuple[str, int, int, int]] = {}
    for pak in package_paths:
        try:
            with pak.open('rb') as f:
                header = f.read(32)
                if len(header) < 32 or header[:4] != b'PACK':
                    continue
                count, index_offset = struct.unpack_from('<II', header, 4)
                f.seek(index_offset)
                for _ in range(count):
                    record = f.read(16)
                    if len(record) != 16:
                        break
                    uid, offset, size, flag = struct.unpack('<IIii', record)
                    index.setdefault(uid & 0xffffffff, (str(pak), offset, size, flag))
        except Exception as ex:
            print(f'WARN: failed to index {pak}: {ex}', file=sys.stderr)
    return index


def stage_requirements(requirements: dict[str, dict[str, Any]], index: dict[int, tuple[str, int, int, int]],
                       out_root: Path, extract: bool, npcres_paths: dict[str, str],
                       npcres_sprites: dict[str, list[str]]) -> list[dict[str, Any]]:
    out_root.mkdir(parents=True, exist_ok=True)
    catalog: list[dict[str, Any]] = []
    for res_type, entry in sorted(requirements.items()):
        staged = []
        missing = []
        for source_path in source_paths_for_res_type(res_type, npcres_paths, npcres_sprites):
            data = extract_spr(index, source_path)
            if data is None:
                missing.append(source_path.lstrip('\\'))
                continue
            uid = jx.compute_path_uid(source_path)
            if extract:
                (out_root / f'{uid}.spr').write_bytes(data)
            staged.append({
                'action': action_from_path(source_path, res_type),
                'sourcePath': source_path.lstrip('\\'),
                'uid': uid,
                'bytes': len(data),
            })
        catalog.append({
            'resType': res_type,
            'folder': entry['folder'],
            'templateIds': entry['templateIds'],
            'staged': staged,
            'missingSourcePaths': missing,
            'hasRuntimeSprite': len(staged) > 0,
        })
    return catalog


def main() -> int:
    parser = argparse.ArgumentParser(description='Stage NPC SPR files used by generated PC Region_S spawns.')
    parser.add_argument('--unity-root', type=Path, default=UNITY_ROOT)
    parser.add_argument('--pc-root', type=Path, default=PC_ROOT)
    parser.add_argument('--region-root', type=Path, default=None)
    parser.add_argument('--npc-file', type=Path, default=None)
    parser.add_argument('--out-root', type=Path, default=None)
    parser.add_argument('--catalog-root', type=Path, default=None)
    parser.add_argument('--extra-template-id', type=int, action='append', default=[],
                        help='Also stage the NpcResType for this NpcS template row (repeatable).')
    parser.add_argument('--extra-res-type', action='append', default=[],
                        help='Also stage this NpcResType even when it is not referenced by Region_S (repeatable).')
    parser.add_argument('--extract', action='store_true')
    parser.add_argument('--clean', action='store_true')
    args = parser.parse_args()

    unity_root = args.unity_root.resolve()
    pc_root = args.pc_root.resolve()
    region_root = args.region_root or unity_root / 'Assets/StreamingAssets/Generated/MapServerRegions'
    npc_file = args.npc_file or unity_root / 'Assets/StreamingAssets/Reference/PcNpc/npcs.txt'
    out_root = args.out_root or unity_root / 'Assets/StreamingAssets/Generated/NpcSprites'
    catalog_root = args.catalog_root or unity_root / 'Assets/StreamingAssets'
    if args.extract and args.clean and out_root.exists():
        shutil.rmtree(out_root)
    start = time.time()
    rows = read_npc_rows(npc_file)
    requirements = collect_requirements(region_root, rows, args.extra_template_id, args.extra_res_type)
    npcres_paths = load_npcres_paths(pc_root)
    npcres_sprites = load_npcres_sprite_rows(pc_root)
    packages = client_package_order(pc_root)
    index = build_priority_index(packages)
    catalog_entries = stage_requirements(requirements, index, out_root, args.extract, npcres_paths, npcres_sprites)
    staged_count = sum(len(e['staged']) for e in catalog_entries)
    res_with_runtime = sum(1 for e in catalog_entries if e['hasRuntimeSprite'])
    missing_runtime = [e['resType'] for e in catalog_entries if not e['hasRuntimeSprite']]

    now = utc_now()
    catalog = {
        'schemaVersion': 1,
        'generatedAtUtc': now,
        'sourceRoot': str(pc_root),
        'sourceNpcFile': str(npc_file),
        'sourceRegionRoot': str(region_root),
        'sourcePackages': [str(p) for p in packages],
        'npcresPathRows': len(npcres_paths),
        'npcresSpriteRows': len(npcres_sprites),
        'spriteFolder': 'Generated/NpcSprites',
        'uniqueResTypes': len(catalog_entries),
        'resTypesWithRuntimeSprite': res_with_runtime,
        'entries': catalog_entries,
    }
    coverage = {
        'schemaVersion': 1,
        'generatedAtUtc': now,
        'phase': 'phase3_npc_spr_visual_staging',
        'sourceRoot': str(pc_root),
        'sourceNpcFile': str(npc_file),
        'sourceRegionRoot': str(region_root),
        'sourcePackages': [str(p) for p in packages],
        'npcresPathRows': len(npcres_paths),
        'npcresSpriteRows': len(npcres_sprites),
        'uniqueResTypes': len(catalog_entries),
        'resTypesWithRuntimeSprite': res_with_runtime,
        'resTypesMissingRuntimeSprite': len(missing_runtime),
        'stagedSprites': staged_count,
        'missingRuntimeResTypes': missing_runtime,
        'elapsedSeconds': round(time.time() - start, 3),
    }
    catalog_path = catalog_root / 'NpcSpriteCatalog.json'
    coverage_path = catalog_root / 'NpcSpriteCoverage.json'
    write_json(catalog_path, catalog)
    write_json(coverage_path, coverage)
    make_meta(catalog_path)
    make_meta(coverage_path)
    print(json.dumps(coverage, ensure_ascii=False, indent=2))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
