// -----------------------------------------------------------------------------
// VLTK.Survivor — SkillDef
// ScriptableObject skill definition for the Survivor mode (ticket 26 D2).
// Data mirror of SkillRow; assets generated by the editor menu
// (VLTK/Survivor/Generate Skill Catalog). Fail-closed: PreCastSprUid /
// ChildMissile.AnimFileUid = "" when the SPR is not staged — consumers must
// fall back to the color proxy, never fabricate a path.
// -----------------------------------------------------------------------------

using UnityEngine;

namespace VLTK.Survivor
{
    [CreateAssetMenu(fileName = "SkillDef", menuName = "VLTK/Survivor/SkillDef")]
    public class SkillDef : ScriptableObject
    {
        public int Id;
        public string Name;
        public string Desc;

        /// <summary>LvlSetScript dir key (shaolin, tianwang, special, npc, ...).</summary>
        public string Faction;
        public SurvivorSkillPool Pool;
        public bool InDisplayFile;

        public int Form;            // 7 = ranged dominant, 12 = melee (outside SkillMissileForm enum)
        public bool IsMelee;
        public int WaitTime;            // PC WaitTime (col 27, ticks 1/16s)
        public bool SpawnsMissile;
        public bool IsAura;

        public int ChildMissileId;
        public MissileVisualInfo ChildMissile; // null = fail-closed

        /// <summary>col 22 ChildSkillNum — số đạn fan spread (PC m_nChildSkillNum).</summary>
        public int ChildSkillNum;

        public string PreCastPath;
        public string PreCastSprUid; // "" = not staged → proxy

        public int FanParam1; // 1/64 vòng
        public int FanParam2; // px

        public int ReqLevel;
        public int MaxLevel;

        public int AttackRadius;
        public float TimePerCast;
        public bool IsPhysical;

        public string[] LvlScripts = new string[20];
        public int[] LvlData = new int[20];

        public SurvivorSupplyTag SupplyTag;

        public static SkillDef FromRow(SkillRow row)
        {
            var def = CreateInstance<SkillDef>();
            def.Id = row.Id;
            def.Name = row.Name;
            def.Desc = row.Desc;
            def.Faction = row.Faction;
            def.Pool = row.Pool;
            def.InDisplayFile = row.InDisplayFile;
            def.Form = row.Form;
            def.IsMelee = row.IsMelee;
            def.WaitTime = row.WaitTime;
            def.SpawnsMissile = row.SpawnsMissile;
            def.IsAura = row.IsAura;
            def.ChildMissileId = row.ChildMissileId;
            def.ChildSkillNum = row.ChildSkillNum;
            def.ChildMissile = row.ChildMissile == null ? null : new MissileVisualInfo
            {
                Id = row.ChildMissile.Id,
                AnimFileUid = row.ChildMissile.AnimFileUid,
                MoveKind = row.ChildMissile.MoveKind,
                Speed = row.ChildMissile.Speed,
                LifeTime = row.ChildMissile.LifeTime,
                ResponseSkill = row.ChildMissile.ResponseSkill,
            };
            def.PreCastPath = row.PreCastPath;
            def.PreCastSprUid = row.PreCastSprUid;
            def.FanParam1 = row.FanParam1;
            def.FanParam2 = row.FanParam2;
            def.ReqLevel = row.ReqLevel;
            def.MaxLevel = row.MaxLevel;
            def.AttackRadius = row.AttackRadius;
            def.TimePerCast = row.TimePerCast;
            def.IsPhysical = row.IsPhysical;
            System.Array.Copy(row.LvlScripts, def.LvlScripts, row.LvlScripts.Length);
            System.Array.Copy(row.LvlData, def.LvlData, row.LvlData.Length);
            def.SupplyTag = row.SupplyTag;
            return def;
        }
    }
}
